apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: p-fazliddin
  name: pod-deploy-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]
